#!/bin/bash

GREEN='\033[0;32m'
NC='\033[0m'
iname=$(ip -o link show | sed -rn '/^[0-9]+: en/{s/.: ([^:]*):.*/\1/p}')
echo -e "${GREEN}Determining subnet...${NC}"
ip_addr=$(/sbin/ifconfig "$iname" | grep "inet " | awk '{print $2}')
ip_subnet=$(echo $ip_addr | cut -d'.' -f1,2,3)
ip_subnet+=".0/24"
echo -e "${GREEN}Done. Subnet found is '$ip_subnet'${NC}"
echo -e "${GREEN}Define targets...${NC}"
targets=$(nmap -n -sn $ip_subnet  -oG - | awk '/Up$/{print $2}' | paste -sd ",")
targetsnbr=$($targets | wc -l)
echo -e "${GREEN}Done. Found '$targetnbr' targets${NC}"
echo -e "${GREEN}Run vulnerability scan...${NC}"
docker run --rm -v $(pwd):/reports/:rw kptainflintt/lazyvuln python3 -u scan.py $targets --update -o scan_$(date -I).xml -f XML -t "Consider Alive"
echo -e "${GREEN}Vulnerability scan done. XML report wrote, sending to Faraday${NC}"
sleep 5
faraday-cli auth -f http://localhost:5985 -u faraday -p Fireport! && faraday-cli workspace create scan_$(date -I) && faraday-cli tool report ./scan_$(date -I).xml
echo -e "${GREEN}Done. You ara able to find your new workspace on Faraday WebUI${NC}"
